### ISSUE TITLE
Could not find pry-coolline-0.1.1 in any of the sources

### ISSUE THREAD

**Issue by dlupu** [Tapjoy/acts_as_approvable#17]
Hello

I'm trying to install acts_as_approvable but bundler does not seem to find the pry-coolline gem. Any idea why?

Thanks
Dorian

**Comment by dlupu** [comment]
Actually I've forked the project and I'm trying to read / edit / contribute to the code. But when i try to bundle install the dependencies I'm getting the error in the title

```
bundle install
Fetching source index for http://rubygems.org/  
Could not find pry-coolline-0.1.1 in any of the sources
```

**Comment by jlogsdon** [comment]
Well... apparently the gem was yanked! I'll remove it from the gemspec.
