### ISSUE TITLE
Problem when using Single Table Inheritance

### ISSUE THREAD

**Issue by dlupu** [Tapjoy/acts_as_approvable#19]
Hello, 

I'm starting to use this gem inside one of my current projects and I think I came across a small bug. I'm using Single Table Inheritance and I would like to use acts_as_approvable inside the base class, like this:

```
 class Blobs::Blob < ActiveRecord::Base
    acts_as_approvable :state_field => :approval_state, :on => [:create, :update]
 end

 class Blobs::SmallText < Blobs::Blob
 end
```

When I try to create a SmallText model I get the following error.

```
  SystemStackError: stack level too deep /Users/dlupu/.rvm/gems/ruby-1.9.2-p290@xyz/gems/activerecord-3.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:206:
```

Removing the acts_as_approvable line fixes the error.

I've tried to add the this line in each child class but I still get the error:

```
class Blobs::Blob < ActiveRecord::Base
 end

class Blobs::SmallText < Blobs::Blob
    acts_as_approvable :state_field => :approval_state, :on => [:create, :update]
 end
```

**Comment by dlupu** [comment]
Update: I've disabled STI but I still get the error. Maybe its the fact that I'm using a module (I'll try without it and get back).

**Comment by dlupu** [comment]
Seems that the problem was that I used "approval_state" to name the "state_field". Replacing that with "state" fixed the problem. Would be nice if you could update the readme file.

**Comment by jlogsdon** [comment]
Yeah, I realized recently the documentation for that is sub-par. I'll make a note to update it for the next release.
