### ISSUE TITLE
Storage type of state

### ISSUE THREAD

**Issue by nwigginsTJ** [Tapjoy/acts_as_approvable#6]
I think it makes more sense to store the state on the backend as an Integer/SmallInt, since the database operations would be cheaper. Since the states are really just constants, the plugin can manage the mapping of these states to strings.

**Comment by jlogsdon** [comment]
I see what you mean. I'll work that out in my next batch of updates.

**Comment by jlogsdon** [comment]
448908505 fixes this issue.
